import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import localFont from 'next/font/local'
import { ThemeConfig } from '@/@core/theme/ThemeComponent'

const myFont = localFont({ src: '../../public/fonts/IRANSansWeb.woff2', display: 'swap' })
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body dir='rtl' className={myFont.className}>
          <Navbar />
          {children}
      </body>
    </html>
  )
}
